import { Vector } from './vector';
import {
  isEqual,
  getEpsilon,
  changeEpsilon,
  round,
  roundWithStep,
} from './helpers';
import {
  arrayUnaryOperation,
  arrayBinaryOperation,
  concatArrays,
  concatMatrices,
  concatTensors,
  setMatrixMainDiagonal,
  setTensorMainDiagonal,
  makeMatrixSymmetric,
  makeTensorSymmetric,
  sortedNumbers,
  weighArray,
  weighMatrix,
  normalizeArray,
  normalizeMatrixColumns,
} from './operations';
import {
  createVector,
  toVector,
  createFilledArray,
  createEmptyMatrix,
  createEmptyTensor,
  repeatArrayValues,
} from './factories';
import {
  createRandomInteger,
  createRandomFloat,
  randomizeMatrix,
  getIndexByFrequencies,
} from './random';

export {
  Vector,
  createVector,
  toVector,
  createFilledArray,
  createEmptyMatrix,
  createEmptyTensor,
  createRandomInteger,
  createRandomFloat,
  repeatArrayValues,
  randomizeMatrix,
  getIndexByFrequencies,
  isEqual,
  getEpsilon,
  changeEpsilon,
  arrayUnaryOperation,
  arrayBinaryOperation,
  concatArrays,
  concatMatrices,
  concatTensors,
  setMatrixMainDiagonal,
  setTensorMainDiagonal,
  makeMatrixSymmetric,
  makeTensorSymmetric,
  sortedNumbers,
  weighArray,
  weighMatrix,
  normalizeArray,
  normalizeMatrixColumns,
  round,
  roundWithStep,
};
