export const PROVIDED_CLEAR_ATOMS = Symbol('PROVIDED_CLEAR_ATOMS');
export const PROVIDED_REFILL_ATOMS = Symbol('PROVIDED_REFILL_ATOMS');
export const PROVIDED_OPEN_RANDOMIZE_CONFIG = Symbol('PROVIDED_OPEN_RANDOMIZE_CONFIG');
