name: Genetic Search

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4

      - name: Build
        run: |
          npm install

      - name: Start
        run: |
          npm run tool clusters-grade-maximize typesCount=6
